onlyBuiltDependencies:
  - esbuild

allowBuilds:
  esbuild: true
  protobufjs: set this to true or false
  sharp: set this to true or false
  unrs-resolver: false

ignoredBuiltDependencies:
  - unrs-resolver
